name: Terraform Validate

on:
  push:
    branches:
      - master

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - confluence-agent-terraform
          - slack_bot/infra
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Plan
        env:
          TF_VAR_aws_region: us-east-1
          TF_VAR_knowledge_base_name: test-kb
          TF_VAR_knowledge_base_description: test desc
          TF_VAR_agent_name: test-agent
          TF_VAR_agent_description: test agent desc
          TF_VAR_foundation_model: test-model
          TF_VAR_agent_instruction: test instruction
          TF_VAR_tags: '{}'
          TF_VAR_agent_type: KNOWLEDGE_BASE
          TF_VAR_confluence_host_url: https://dummy.confluence
          TF_VAR_confluence_api_key: dummy-api-key
          TF_VAR_tenant: dummy-tenant
          TF_VAR_env: test
          TF_VAR_agent_api_url: https://dummy.agent
          TF_VAR_slack_secret_name: dummy-slack-secret
          TF_VAR_slack_bot_token: dummy-bot-token
          TF_VAR_slack_signing_secret: dummy-signing-secret
          TF_VAR_lambda_zip_path: ''
          TF_VAR_create_lambda_file: 'true'
        run: terraform plan -input=false -no-color || true
        # Note: '|| true' allows plan to succeed even if not all resources can be created with dummy values. 